baseURL = "https://bobby.dioriza.com/"
languageCode = "en-us"
title = "Bobby Ananta Dioriza"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changeFreq = "monthly"
  priority = 0.8
  filename = "sitemap.xml"

[taxonomies]
